### PR TITLE
Kevin's update README

### PR DESCRIPTION
**Pull request by kevinyu98**
Hello All:
Can you help review this change? I have successfully test the DSX Desktop with HDP on cluster. So I updated the README with the procedure I did.

I remove the the setup Step1 for the HDP sandbox part, because the HDP sandbox doesn't have matching image with this code pattern environment.

In step 2, I removed the first three steps in the HDP search part, because we are missing step 0 part
```
# vi /etc/yum/pluginconf.d/priorities.conf 
[main]
enabled = 0
```

also the instruction may changes and it is kind of redundant to copy here.

thanks.

### CODE REVIEW

**Comment by dilipbiswal** [comment]
I have put some comments under https://github.com/IBM/hdp-search-spark-recommender/pull/10.

**Comment by dilipbiswal** [comment]
LGTM

**Comment by dilipbiswal** [comment]
@stevemart.. i am happy with the content. I will merge in a few hours. If you have some comments do let us know.. or else we can handle it in new prs. Thanks !!

**Review by stevemar — APPROVED** [review]
Dilip, I'm happy with the changes as-is. The only thing I noticed is the numbering change broke there step links. I'll create a PR for that in a bit. Happy to merge this. Thanks for all the work Kevin.

**Comment by kevinyu98** [comment]
thanks a lot

**Pull request merged**
